### ISSUE TITLE
VBoxManage not found on windows

### ISSUE THREAD

**Issue by hoavt** [teracyhq-incubator/teracy-dev-core#19]
After fetching the latest code of teracy-dev, vagrant up is not working
```
```Administrator@8EIPUXSN50GYWXU /cygdrive/f/teracy/teracy-dev
$ vagrant up
[TeracyDev::Location::GitSynch][INFO]: cd F:/teracy/teracy-dev/lib/../extensions && git clone https://github.com/teracyhq-incubator/teracy-dev-core.git
F:/teracy/teracy-dev/lib/teracy-dev/location/git_synch.rb:59:in `block in sync'
Cloning into 'teracy-dev-core'...
remote: Counting objects: 171, done.
remote: Compressing objects: 100% (95/95), done.
Receiving objectsremote: Total 171 (delta 74), reused 165 (delta 69), pack-reused 0
Receiving objects: 100% (171/171), 28.47 KiB | 170.00 KiB/s, done.
Resolving deltas: 100% (74/74), done.
[TeracyDev::Location::GitSynch][INFO]: cd F:/teracy/teracy-dev/lib/../extensions/teracy-dev-core && git checkout v0.2.0
F:/teracy/teracy-dev/lib/teracy-dev/location/git_synch.rb:64:in `block in sync'
Note: checking out 'v0.2.0'.
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:
  git checkout -b <new-branch-name>
HEAD is now at ded0fc7 Merge pull request #14 from hoatle/tasks/#13-v0.2.0-release
F:/teracy/teracy-dev/extensions/teracy-dev-core/lib/teracy-dev-core/config/virtualbox_provider.rb:17:in ``': No such file or directory - VBoxManage --version (Errno::ENOENT)
        from F:/teracy/teracy-dev/extensions/teracy-dev-core/lib/teracy-dev-core/config/virtualbox_provider.rb:17:in `block in configure_node'
        from F:/teracy/teracy-dev/extensions/teracy-dev-core/lib/teracy-dev-core/config/virtualbox_provider.rb:11:in `each'
        from F:/teracy/teracy-dev/extensions/teracy-dev-core/lib/teracy-dev-core/config/virtualbox_provider.rb:11:in `configure_node'
        from F:/teracy/teracy-dev/lib/teracy-dev/config/configurator.rb:17:in `configure'
        from F:/teracy/teracy-dev/lib/teracy-dev/config/manager.rb:33:in `block in configure'
        from F:/teracy/teracy-dev/lib/teracy-dev/config/manager.rb:32:in `each'
        from F:/teracy/teracy-dev/lib/teracy-dev/config/manager.rb:32:in `configure'
        from F:/teracy/teracy-dev/lib/teracy-dev/loader.rb:135:in `configure'
        from F:/teracy/teracy-dev/lib/teracy-dev/loader.rb:148:in `block (3 levels) in configure_vagrant'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/config/v2/loader.rb:37:in `load'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/config/loader.rb:126:in `block (2 levels) in load'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/config/loader.rb:119:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/config/loader.rb:119:in `block in load'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/config/loader.rb:116:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/config/loader.rb:116:in `load'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/vagrantfile.rb:166:in `machine_config'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/environment.rb:322:in `default_provider'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/plugin/v2/command.rb:177:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/plugin/v2/command.rb:204:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/plugin/v2/command.rb:186:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/plugin/v2/command.rb:186:in `with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/plugins/commands/up/command.rb:87:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/cli.rb:54:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/environment.rb:275:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/bin/vagrant:156:in `<main>'
Administrator@8EIPUXSN50GYWXU /cygdrive/f/teracy/teracy-dev
````

Try the command "VBoxManage" ==> the command is not found

**Comment by phuonglm** [comment]
Need to add `/cygdrive/c/HashiCorp/Vagrant/bin:/cygdrive/c/Program Files/Oracle/VirtualBox` to PATH of cygwin

**Comment by datphan** [comment]
You have to add `vagrant` and `virtualbox` to PATH of window

Press `WINDOW` button then type `Edit the system environment variables`, enter
Press `n` or click `Environment Variables` button
Double click `Path`, then click `New` and `Browse`, locate `/HashiCorp/Vagrant/bin` and `/Program Files/Oracle/VirtualBox`
Click `OK`,  relaunch `Cygwin`

**Comment by hoatle** [comment]
@datphan @phuonglm can we automate that?

**Comment by datphan** [comment]
maybe a bash script when vagrant up?

```
setx path "%PATH%;C:\HashiCorp\Vagrant\bin;C:\Program Files\Oracle\VirtualBox" 
```

**Comment by hoatle** [comment]
when vagrant is used, PATH should be updated to include vagrant, virtualbox if there is no vagrant, virtualbox path yet.

Note that we need to find the actual current working vagrant, virtualbox working path to check and add.

**Comment by hoatle** [comment]
I guess we can use this: https://github.com/hashicorp/vagrant/blob/85acf0cac724ef4bfda593a66e0c17f7e4110da0/plugins/providers/virtualbox/driver/meta.rb#L23 to get the virtualbox version instead of using `VBoxManager`

**Comment by hoatle** [comment]
assigned to @hoavt to verify

**Comment by hoatle** [comment]
@hoavt it's expected that users don't have to update anything related to PATH, just use teracy-dev (as long as virtualbox and vagrant are installed)

**Comment by hoavt** [comment]
confirmed
