### ISSUE TITLE
should not delete existing key (networks and synced_folders)

### ISSUE THREAD

**Issue by hoatle** [teracyhq-incubator/teracy-dev-core#7]
expected:

networks and sync_folders should be available for configuring nodes

actual:

networks and sync_folders was empty

**Comment by hoatle** [comment]
for example, networks was missing from [TeracyDevCore::Config::Networks][DEBUG]

```
[TeracyDev::Config::Manager][DEBUG]: configure node: #<Vagrant::Config::V2::Root:0x0000000102896798> with {"vm"=>{"box"=>"bento/ubuntu-16.04", "box_version"=>nil, "box_url"=>nil, "synced_folders"=>[], "hostname"=>"node-01.local", "networks"=>[{"_id"=>"0", "mode"=>"public_network"}]}, "providers"=>[{"_id"=>"0", "enabled"=>true, "type"=>"virtualbox", "require_version"=>">= 5.2", "gui"=>false, "memory"=>1024, "description"=>"node \#{Time.now.getutc.to_i}"}], "provisioners"=>[{"_id"=>"essential-1", "type"=>"shell", "enabled"=>true, "name"=>"ip-display", "path"=>"workspace/teracy-dev-essential/provisioners/shell/ip_display.sh", "run"=>"always"}], "plugins"=>[], "_id"=>"0", "name"=>"node-01", "primary"=>true}	/Users/hoatle/k8s-dev/lib/teracy-dev/loader.rb:148:in `block (3 levels) in configure_vagrant'

[TeracyDevCore::Config::VM][DEBUG]: configure_node: {"box"=>"bento/ubuntu-16.04", "box_version"=>nil, "box_url"=>nil, "hostname"=>"node-01.local"}	/Users/hoatle/k8s-dev/lib/teracy-dev/config/manager.rb:33:in `block in configure'

[TeracyDevCore::Config::Networks][DEBUG]: configure_networks: []	/Users/hoatle/k8s-dev/lib/teracy-dev/config/configurator.rb:17:in `configure'
```

**Comment by hoatle** [comment]
note: after settings is frozen, it's expected that the settings object is immutable, we should improve this line of code to make it really immutable https://github.com/teracyhq/dev/blob/develop/lib/teracy-dev/loader.rb#L29
